// Generative Art 4 - HSB and Custom Paltes
// Assiya Boulfiza
// March 26, 2024
// working with colour and coour palets generated by numbers and not completly or not random 

let rectWidth = 50;
let rectHeight = 10;
let colors = ["#774F38", "#E08E79", "#F1D4AF", "#ECE5CE", "#C5E0DC"];

function setup() {
  createCanvas(windowWidth, windowHeight);
  noStroke();
  drawRGB(width*0.1);
  drawHSB(width*0.4);
  drawCustom(width*0.7);
}

function drawCustom(x){
  color(RGB);
  let index = 0;
  for(let y = 0; y < height; y += rectHeight){
    fill(colors[index % colors.length]);
    rect(x, y, rectWidth, rectHeight);

    index++;
  }
}

function drawRGB(x) {
  //draw a stack of rectangles at x = x using R, G, B random
  color(RGB);
  for(let y = 0; y < height; y += rectHeight){
    fill(random(255), random(255), random(255));
    rect(x, y, rectWidth, rectHeight);
  }
}

function drawHSB(x) {
  //draw a stack of rectangles at x = x using R, G, B random
  colorMode(HSB);
  for(let y = 0; y < height; y += rectHeight){
    let hue = map(y, 0, height, 0, 360);
    fill(hue, 360, 360);
    rect(x, y, rectWidth, rectHeight);
  }
}
